
deployment:
  tasks:
    - export DEPLOYPATH=/home/baxvcmdv/public_html
    - cp -R resources/views/welcome.blade.php $DEPLOYPATH/resources/views
    - cp -R public/js $DEPLOYPATH/public
    - cp -R public/css $DEPLOYPATH/public
    - cp -R public/images $DEPLOYPATH/public
