
deployment:
  tasks:
    - export DEPLOYPATH=/home/baxvcmdv/public_html
    - cp -R resources/views $DEPLOYPATH/resources
    - cp -R public/js $DEPLOYPATH/public
    - cp -R public/css $DEPLOYPATH/public
    - cp -R public/images $DEPLOYPATH/public
    - cp public/pdftohtml.exe $DEPLOYPATH/public
    - cp -R app/Helpers $DEPLOYPATH/app
    - cp app/Providers/HelperServiceProvider.php $DEPLOYPATH/app/Providers
    - cp -R app/Models $DEPLOYPATH/app
    - cp -R app/Http/Controllers $DEPLOYPATH/app/Http
    - cp -R database/migrations $DEPLOYPATH/database
    - cp lang/en/obem.php $DEPLOYPATH/lang/en
    - cp -R lang/fr $DEPLOYPATH/lang
    - cp -R config/app.php $DEPLOYPATH/config
    - cp routes/web.php $DEPLOYPATH/routes
    - cp index.php $DEPLOYPATH
    - cp php.ini $DEPLOYPATH
    - mv .env.prod $DEPLOYPATH/.env
