
deployment:
  tasks:
    - export DEPLOYPATH=/home/baxvcmdv/public_html
    - cp -R resources $DEPLOYPATH
    - cp -R public/js $DEPLOYPATH/public
    - cp -R public/css $DEPLOYPATH/public
    - cp -R public/images $DEPLOYPATH/public
